create database customer_behavior_da;
select * from customer_behavior limit 10; 

-- Q1. What is the total revenue generated by male vs. female customer?
select gender, sum(purchase_amount) as revenue
from customer_behavior
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer_behavior
where discount_applied = "Yes" and purchase_amount >= (select avg(purchase_amount) from customer_behavior);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as "average product rating"
from customer_behavior
group by item_purchased
order by avg(review_rating) desc 
limit 5;

-- Q4. Compare the average purchase amount between Standard and Express shipping.
select shipping_type, round(avg(purchase_amount),2) as "average purchase amount"
from customer_behavior
where shipping_type in ('Standard', 'Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare: Average spend, Total revenue between subscribed and non-subscribed customers.
select subscription_status, sum(purchase_amount) as 'revenue', round(avg(purchase_amount),2) as "average purchase amt" 
from customer_behavior
group by subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with a discount applied?
select item_purchased,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as "discount_rate" 
from customer_behavior
group by item_purchased 
order by discount_rate desc
limit 5;

-- Q7. Segment customers into: New, Returning, Loyal based on the total number of previous purchases and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
case 
    when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then "Returning"
    else "Loyal"
    end as customer_segment
from customer_behavior
)

select customer_segment, count(*) as "Number of customers"
from customer_type
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select category, 
count(customer_id) as total_order, 
item_purchased,
row_number() over(partition by category order by count(customer_id) desc)as item_rank
from customer_behavior
group by category, item_purchased
)
select item_rank, category, item_purchased, total_order
from item_counts
where item_rank <= 3; 

-- Q9. Are repeat buyers (customers with more than 5 previous purchases) also more likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer_behavior
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the revenue contributed by each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer_behavior
group by age_group
order by total_revenue desc;



